name: Pages
uses: peaceiris/actions-gh-pages@v3.7.3
with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  publish_dir: ./build/web
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request: